# Generated by Django 4.2.9 on 2025-04-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coupon_used',
        ),
    ]
