name: Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3

        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Cloud
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_CONNECTION }} << 'EOF'
          cd /home/ec2-user/workspace/TejasVaij_DRF_Backend
          git pull origin main
          source /home/ec2-user/workspace/venv/bin/activate
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py migrate --run-syncdb
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          EOF
